#!/usr/bin/env bash

set -e

payload=$(cat <&0)

CURRENT_VERSION=$(echo $payload | jq -r '.version // ""')

if [[ -z "$CURRENT_VERSION" ]]; then
   CURRENT_VERSION="{\"timestamp\": \"$(date +%s)\"}"
fi

echo "{\"version\" : $CURRENT_VERSION, \"metadata\" : [] }"
